services:
  standai_stt_app:
    container_name: standai_stt_app
    image: standai_stt_app:latest
    build:
      context: .   # 当前目录作为构建上下文
      dockerfile: Dockerfile   # Dockerfile 路径
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app   # 将项目文件夹挂载到容器内
    environment:
      - FLASK_APP=main.py  # 设置 Flask 应用入口
      - FLASK_ENV=production  # 设置 Flask 环境为生产环境
    restart: always
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - standai_stt_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
